// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportChecker.DataAccess;

#nullable disable

namespace ReportChecker.DataAccess.Migrations
{
    [DbContext(typeof(ReportCheckerDbContext))]
    [Migration("20260425075516_LlmCoefficients")]
    partial class LlmCoefficients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CheckEntity", b =>
                {
                    b.Property<Guid>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CheckId");

                    b.HasIndex("ReportId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProgressStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CommentId");

                    b.HasIndex("IssueId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CommentReadEntity", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommentId", "UserId");

                    b.ToTable("CommentReads");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.FileCheckSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CheckId")
                        .IsUnique();

                    b.ToTable("FileCheckSources");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.FileReportSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntryFilePath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("InitialFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("FileReportSources");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.GitHubCheckSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CheckId")
                        .IsUnique();

                    b.ToTable("GitHubCheckSources");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.GitHubReportSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("GitHubReportSources");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.InstructionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.InstructionTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Mode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("InstructionTasks");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.IssueEntity", b =>
                {
                    b.Property<Guid>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chapter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IssueId");

                    b.HasIndex("CheckId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LlmModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("InputCoefficient")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("OutputCoefficient")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("LlmModels");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LlmUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ReportId");

                    b.ToTable("LlmUsages");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LocalCheckSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CheckId")
                        .IsUnique();

                    b.ToTable("LocalCheckSources");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LocalReportSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientMachineName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntryFilePath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("InitialFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("LocalReportSources");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.PatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.PatchLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousContent")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatchId");

                    b.ToTable("PatchLines");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.ReportEntity", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("LlmModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ReportId");

                    b.HasIndex("LlmModelId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.SubscriptionOfferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("SubscriptionOffers");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.SubscriptionPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportsLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TokensLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.UserSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultPricePerMonth")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LinkedSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LinkedSubscriptionId");

                    b.HasIndex("ParentSubscriptionId");

                    b.HasIndex("PlanId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CheckEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithMany("Checks")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CommentEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.IssueEntity", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CommentReadEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.CommentEntity", "Comment")
                        .WithMany("Reads")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.FileCheckSourceEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.CheckEntity", "Check")
                        .WithOne("FileSource")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.FileCheckSourceEntity", "CheckId");

                    b.Navigation("Check");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.FileReportSourceEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithOne("FileSource")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.FileReportSourceEntity", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.GitHubCheckSourceEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.CheckEntity", "Check")
                        .WithOne("GitHubSource")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.GitHubCheckSourceEntity", "CheckId");

                    b.Navigation("Check");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.GitHubReportSourceEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithOne("GitHubSource")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.GitHubReportSourceEntity", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.InstructionEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithMany("Instructions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.InstructionTaskEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithMany("InstructionTasks")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.IssueEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.CheckEntity", "Check")
                        .WithMany("Issues")
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LlmUsageEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.LlmModelEntity", "Model")
                        .WithMany("Usages")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithMany("Usages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LocalCheckSourceEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.CheckEntity", "Check")
                        .WithOne("LocalSource")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.LocalCheckSourceEntity", "CheckId");

                    b.Navigation("Check");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LocalReportSourceEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.ReportEntity", "Report")
                        .WithOne("LocalSource")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.LocalReportSourceEntity", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.PatchEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.CommentEntity", "Comment")
                        .WithOne("Patch")
                        .HasForeignKey("ReportChecker.DataAccess.Entities.PatchEntity", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.PatchLineEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.PatchEntity", "Patch")
                        .WithMany("Lines")
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.ReportEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.LlmModelEntity", "LlmModel")
                        .WithMany("Reports")
                        .HasForeignKey("LlmModelId");

                    b.Navigation("LlmModel");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.SubscriptionOfferEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.SubscriptionPlanEntity", "Plan")
                        .WithMany("Offers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.UserSubscriptionEntity", b =>
                {
                    b.HasOne("ReportChecker.DataAccess.Entities.UserSubscriptionEntity", "LinkedSubscription")
                        .WithMany("LinkedSubscriptions")
                        .HasForeignKey("LinkedSubscriptionId");

                    b.HasOne("ReportChecker.DataAccess.Entities.UserSubscriptionEntity", "ParentSubscription")
                        .WithMany("ChildrenSubscriptions")
                        .HasForeignKey("ParentSubscriptionId");

                    b.HasOne("ReportChecker.DataAccess.Entities.SubscriptionPlanEntity", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedSubscription");

                    b.Navigation("ParentSubscription");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CheckEntity", b =>
                {
                    b.Navigation("FileSource");

                    b.Navigation("GitHubSource");

                    b.Navigation("Issues");

                    b.Navigation("LocalSource");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.CommentEntity", b =>
                {
                    b.Navigation("Patch");

                    b.Navigation("Reads");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.IssueEntity", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.LlmModelEntity", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.PatchEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.ReportEntity", b =>
                {
                    b.Navigation("Checks");

                    b.Navigation("FileSource");

                    b.Navigation("GitHubSource");

                    b.Navigation("InstructionTasks");

                    b.Navigation("Instructions");

                    b.Navigation("LocalSource");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.SubscriptionPlanEntity", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("ReportChecker.DataAccess.Entities.UserSubscriptionEntity", b =>
                {
                    b.Navigation("ChildrenSubscriptions");

                    b.Navigation("LinkedSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
